# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'OpenSSLWrapperTest' do
 pod 'Godzippa'
 pod 'OpenSSL'
end

target 'CTOpenSSLWrapper' do
 pod 'Godzippa'
 pod 'OpenSSL'
end

target 'CTOpenSSLWrapperTests' do

end

